### ISSUE TITLE
getting error in extracting frames

### ISSUE THREAD

**Issue by Nauman007** [hammad001/TSN#1]
Hi @hammad001  , i am using  your code to extract he frames but i am facing this error... it does extract the frames but gets halted while doing so... this is the error i am facing..

Traceback (most recent call last):
  File "vid2img_UCF101.py", line 59, in <module>
    file_list = list(map(dump_frames, vid_list))
  File "vid2img_UCF101.py", line 30, in dump_frames
    cv2.imwrite('{}/{:06d}.jpg'.format(out_full_path, i), frame)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

**Comment by bdytx5** [comment]
solution?

**Comment by Nauman007** [comment]
#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import glob
import sys
import cv2
import argparse

out_path = ''

count = 0
def dump_frames(vid_path,num_of_videos):

    video = cv2.VideoCapture(vid_path)
    vid_name = vid_path.split('/')[-1].split('.')[0]
    out_full_path = os.path.join(out_path, vid_name)

    fcount = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    try:
        os.mkdir(out_full_path)
    except OSError:
        pass
    file_list = []
    for i in list(range(fcount - 1)):
        (ret, frame) = video.read()
        resizedFrame = cv2.resize(frame, (64, 64))
        assert ret, 'Err: {} - {}'.format(vid_name, i)
        cv2.imwrite('{}/img_{:05d}.jpg'.format(out_full_path, i+1), resizedFrame)
        access_path = '{}/img_{:05d}.jpg'.format(vid_name, i+1)
        file_list.append(access_path)
    global count 
    count = count + 1
    print ('--> {}/{} -> {} done'.format(count,num_of_videos,vid_name))
    sys.stdout.flush()
    return file_list


if __name__ == '__main__':
    parser = \
        argparse.ArgumentParser(description='extract frames from videos'
                                )
    parser.add_argument('src_dir')
    parser.add_argument('out_dir')
    parser.add_argument('--ext', type=str, default='mp4', choices=['avi', 'mp4'], help='video file extensions')

    args = parser.parse_args()

    out_path = args.out_dir
    src_path = args.src_dir
    ext = args.ext
    #count = 0

    if not os.path.isdir(out_path):
        print ('creating folder: ' + out_path)
        os.makedirs(out_path)

    vid_list = glob.glob(src_path + '/*/*.' + ext)
    print ('total number of videos found: ', len(vid_list))

    try:
        os.mkdir(out_path)
    except OSError:
        pass

    for vid in vid_list:
        dump_frames(vid,len(vid_list))

**Comment by Nauman007** [comment]
you can use the aabove code i did minor modification ... 
remember i am resizing the images to 64x64 u can chnage this to your desired one or default one

**Comment by bdytx5** [comment]
Thanks bro!!

**Comment by bdytx5** [comment]
had to make a slight modification ... not sure what the issue is but sometimes ret = false ...
import shutil
`

    for i in list(range(fcount - 1))
        (ret, frame) = video.read()
        if not ret:
            shutil.rmtree(out_full_path)
            break
`

**Comment by bdytx5** [comment]
May also need to refactor this function as shown, since some training examples will be missing due to the mod made above`
def build_split_list(split_tuple, frame_info, split_idx, shuffle=False):
    split = split_tuple[split_idx]

    def build_set_list(set_list):
        rgb_list, flow_list = list(), list()
        for item in set_list:
            try:
                frame_dir = frame_info[0][item[0]]
                rgb_cnt = frame_info[1][item[0]]
                flow_cnt = frame_info[2][item[0]]
            except:
                pass
            rgb_list.append('{} {} {}\n'.format(frame_dir, rgb_cnt, item[1]))
            flow_list.append('{} {} {}\n'.format(frame_dir, flow_cnt, item[1]))
        if shuffle:
            random.shuffle(rgb_list)
            random.shuffle(flow_list)
        return rgb_list, flow_list

    train_rgb_list, train_flow_list = build_set_list(split[0])
    test_rgb_list, test_flow_list = build_set_list(split[1])
    return (train_rgb_list, test_rgb_list), (train_flow_list, test_flow_list)


`
